In [9]:
import pandas as pd
import numpy as np
import os

from texter.utils.config_utils import sklearn_model_config as smc
from texter.utils.config_utils import sklearn_data_config as sdc
from texter.utils.text_utils import text_vectorizer
from texter.utils.eval_utils import classifier_report

In [10]:
text_path = "../../../citi/citi_rest/data/raw_data/"
text_labels = os.listdir(text_path)
embpath = "../../data/others/GoogleNews-vectors-negative300-SLIM.bin"

In [3]:
train_data, test_data, train_labels, test_labels, fitted_model = sdc(text_path, text_labels, 
                                                                     embpath, processing_type="tfidf")

In [11]:
rf = smc("RF")
rf.fit(train_data, train_labels)
rf.predict(test_data)

classification model configured to use RandomForestClassifier algorithm.


array([0, 2, 1])

In [12]:
new = "pandas was a great man in a lonely land"
rf.predict(text_vectorizer(new, fitted_model))

array([2])

In [14]:
print(classifier_report(rf, test_data, test_labels, rf.predict(test_data)))

1. score: 0.6666666666666666
2. classification model report:
             precision    recall  f1-score   support

          0       0.00      0.00      0.00         0
          1       1.00      0.50      0.67         2
          2       1.00      1.00      1.00         1

avg / total       1.00      0.67      0.78         3

3. confusion matrix:
[[0 0 0]
 [1 1 0]
 [0 0 1]]
